### ISSUE TITLE
2018 North Sea herring

### ISSUE THREAD

**Issue by arnima-github** [ices-taf/doc#153]
### Summary
https://github.com/ices-taf/2018_her.27.3a47d

### Tasks required
see: https://github.com/ices-taf/doc/blob/master/procedure.md

1: Get model to run

- [x] Contact assessment coordinator
- [x] Get files (data, model) and earlier reports
- [x] Run model

2: Examine the analysis

- [x] Check that data and results resemble earlier reports
- [x] Explore input: data types, files, etc.
- [x] Identify minimal set of files to run the assessment

3: Data script

- [x] Read data files
- [x] Preprocess data
- [x] Write TAF files

4: Input and model scripts

- [x] Prepare model input
- [x] Run model
- [x] Document dependencies, especially non-CRAN packages

5: Output script

- [x] Extract results of interest, e.g. N and F at age
- [x] Construct summary table: Rec, SSB, Fbar, etc.
- [x] Write TAF files

### Links to other issues?
HAWG 2018 TAF work #157

**Comment by colinpmillar** [comment]
links to: HAWG 2018 TAF work #157
