### ISSUE TITLE
Western Baltic herring (taf-sao)

### ISSUE THREAD

**Issue by arni-magnusson** [ices-taf/doc#154]
### Summary
Data preparation and Assessment scripts for Western Baltic herring

### Tasks required
- [ ] Find assessment
- [ ] Western Baltic herring data prep #163
- [ ] Western Baltic herring assessment scripts #164
- [ ] Address emerging issues ...

### links to other issues
a sub task of: HAWG 2018 TAF work #157

**Comment by arni-magnusson** [comment]
2018 discussion.
