### ISSUE TITLE
WGDEEP 2018 TAF work

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#158]
### Summary
Work to support TAF links to WGDEEP- 11/04/2018

### Tasks required
- [x] Contact with chair
- [x] Contact stock assessors
- [x] attend WG
- [ ] Report back progress to WG
- [ ] contribute text section to WG report

### Stocks
2018 Ling 5a #189
2018 Blue ling (5b67) #181
gfb.27.nea - Arni
sbr.27.10 - Arni
