### ISSUE TITLE
NS herring disaggregated data

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#161]
### Summary
Data preparation scripts

### Tasks required
- [ ] Get data files with disaggregated data
- [ ] Revise data.R to read those files
- [ ] Filter, smooth, combine, etc. to create aggregated data

### Links to other issues?
HAWG intersession work #190
2018 North Sea herring #153
