### ISSUE TITLE
North Sea herring assessment scripts

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#162]
### Summary
Assessment scripts for North Sea herring

### Tasks required
- [x] Explore how the model is run
- [x] Script the model run
- [x] Explore what output results belong on TAF
- [x] Script the preparation of TAF output tables

### Links to other issues?
North Sea herring as first TAF assmt #153
