### ISSUE TITLE
Western Baltic herring assessment scripts

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#164]
### Summary
Assessment scripts for Western Baltic herring

### Tasks required
- [ ] Explore how the model is run
- [ ] Script the model run
- [ ] Explore what output results belong on TAF
- [ ] Script the preparation of TAF output tables

### Links to other issues?
Western Baltic herring as TAF-SAO example #154
