### ISSUE TITLE
Daily refresh of a TAF analysis

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#166]
### Summary
For the Benchmark table analysis, it would probably be sufficient to refresh the table every night, or every 12 hours.

### Tasks required
- [ ] implement calling run api from powershell script
- [ ] implement running powershell script as recurrent task on TAF server
- [ ] set up script that lists all repos to be rerun each night

### Links to other issues?
Consider adding a dynamic option to an analysis, where results are always in sync with input DB #105

### useful links
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-6

**Comment by colinpmillar** [comment]
@neil-ices-dk , @Lotte-ices-dk @sarahlmillar @mikeydrew @arnima-github @slarge and Jette,
I have make this issue on TAF to implement the scheduled update of the benchmarks table

**Comment by neil-ices-dk** [comment]
next step to put in the sharepoint test template?

**Comment by colinpmillar** [comment]
Good point - I think we should make it a separate issue though as it has a different set of complications

**Comment by neil-ices-dk** [comment]
@colinpmillar you mean the login issue? well one way forward now that you have taken the update button off the table is that for those that have to login to see 'hidden' fields, is that it the 'login button' just pops the application out in a separate window outside of the sharepoint template. this would be simple and avoid cross posting issues between domains.

**Comment by colinpmillar** [comment]
Actually, I was thinking about how to get round the TAF application not being public yet, and whether to point the sharepoint page to a TAF api (needs page to be public), or to its GitHub address (we ca do that now).  But this can be bundled into this issue.

The login button sounds good - i'll add it to the list :)
