### ISSUE TITLE
Implement online results via a results branch

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#169]
### Summary
Test results being online, using server-data branch that = server-branch (i.e. code) + results

### Tasks required
- [x] Develop logic to create branch from TAF
- [x] develop logic to add code + results to new branch
- [x] implement and test

### Links to other issues?
spawn of: Investigate use of git / svn repository for storing input and output #21

**Comment by colinpmillar** [comment]
done
