### ISSUE TITLE
SmartDots automatic reporting

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#170]
### Summary
Produce an automated standard report on an otolith exchange.  The manager can select settings, such as which strata, e.g. month, to include in the report.

### Tasks required
- [ ] Develop TAF scripts
- [ ] Run in TAF web app
- [ ] develop method to pass arguments to a TAF application
- [ ] test on the April 9th Otolith exchange

### Links to other issues?
at least this:
Consider allowing people to upload a Rmd file to generate a report within TAF #71
