### ISSUE TITLE
Develop VME data processing in TAF

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#171]
### Summary
Modify and tidy current scripts, link inputs to VME DB and upload results directly to VME DB

### Tasks required
- [x] Clean and restructure code into TAF workflow
- [x] Link inputs to VME DB
- [x] update database with results

**Comment by colinpmillar** [comment]
All complete in time for WGDEC group :)
