### ISSUE TITLE
Ecosystem Overview Maps - add to TAF

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#173]
### Summary
Add the code for producing the ecosystem overview maps, and make maps available

### Tasks required
- [ ] Upload and revise code as necessary
- [ ] link to VMS DB
- [ ] Make plots available on GitHub (requires login)
