### ISSUE TITLE
Fisheries overview maps - add to TAF

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#174]
### Summary
Add the code for producing the fisheries overview maps, and make maps available

### Tasks required
- [x] Upload and revise code as necessary
- [x] link to VMS DB
- [x] Make plots available on GitHub (requires login)
