### ISSUE TITLE
Eggs and Larvae data processing

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#175]
### Summary
Develop, make functional and make available the data processing of Eggs and Larvae data 

### Tasks required
- [ ] Develop / clean / restructure code to process data
- [ ] link to DB
- [ ] test on TAF server
