### ISSUE TITLE
OSPAR CEMP tool - station summary page 

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#176]
### Summary
Develop link between OSPAR CEMP tool page, using TAF to generate the html summary page for each station

### Tasks required
- [ ] Restructure code to TAF workflow
- [ ] develop approach to rerun code using different settings / input parameters
- [ ] test on TAF
- [ ] develop link to CEMP webpage - how t we serve the html docs
