### ISSUE TITLE
SID web service access example with data online

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#177]
### Summary
Upload an example of how to access SID to get data categories for each stock

### Tasks required
- [x] Develop and upload code
- [x] Produce a quick html page to allow searching of data offling
- [x] Run on TAF and upload results to GitHub
- [x] share with POs to include in first day presentation

**Comment by colinpmillar** [comment]
data product is here:
https://github.com/ices-taf/DBreport_StockCategories/blob/server/data/StockCategories.csv
