### ISSUE TITLE
WGEF 2018 TAF work

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#179]
### Summary
Work to support TAF links to WGEF - 19/06/2018

### Tasks required
- [ ] Contact with chair
- [ ] Contact stock assessors
- [ ] attend WG
- [ ] Report back progress to WG
- [ ] contribute text section to WG report
