### ISSUE TITLE
2018 Icelandic ling

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#18]
### Summary
https://github.com/ices-taf/2018_lin.27.5a

### Tasks required
see: https://github.com/ices-taf/doc/blob/master/procedure.md

1: Get model to run

- [x] Contact assessment coordinator
- [x] Get files (data, model) and earlier reports
- [x] Run model

2: Examine the analysis

- [ ] Check that data and results resemble earlier reports
- [ ] Explore input: data types, files, etc.
- [ ] Identify minimal set of files to run the assessment

3: Data script

- [ ] Read data files
- [ ] Preprocess data
- [ ] Write TAF files

4: Input and model scripts

- [ ] Prepare model input
- [ ] Run model
- [ ] Document dependencies, especially non-CRAN packages

5: Output script

- [ ] Extract results of interest, e.g. N and F at age
- [ ] Construct summary table: Rec, SSB, Fbar, etc.
- [ ] Write TAF files

### Links to other issues?
WGDEEP 2018 TAF work #158
#137 Contact Rgadget maintainer to ask how results are extracted from Gadget runs

**Comment by neil-ices-dk** [comment]
workshop (special req from Iceland) coming up on Ling (Lotte and David to advise).
