### ISSUE TITLE
2018 Blue ling (5b67)

### ISSUE THREAD

**Issue by arni-magnusson** [ices-taf/doc#181]
### Tasks required
see: https://github.com/ices-taf/doc/blob/master/procedure.md

1: Get model to run

- [ ] Contact assessment coordinator
- [ ] Get files (data, model) and earlier reports
- [ ] Run model

2: Examine the analysis

- [ ] Check that data and results resemble earlier reports
- [ ] Explore input: data types, files, etc.
- [ ] Identify minimal set of files to run the assessment

3: Data script

- [ ] Read data files
- [ ] Preprocess data
- [ ] Write TAF files

4: Input and model scripts

- [ ] Prepare model input
- [ ] Run model
- [ ] Document dependencies, especially non-CRAN packages

5: Output script

- [ ] Extract results of interest, e.g. N and F at age
- [ ] Construct summary table: Rec, SSB, Fbar, etc.
- [ ] Write TAF files

### Links to other issues?
WGDEEP 2018 TAF work #158

**Comment by arnima-github** [comment]
Postponed

**Comment by arni-magnusson** [comment]
2018 discussion.
