### ISSUE TITLE
2018 Icelandic cod

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#184]
### Summary
https://github.com/ices-taf/2018_cod.27.5a

### Tasks required
see: https://github.com/ices-taf/doc/blob/master/procedure.md

1: Get model to run

- [x] Contact assessment coordinator
- [x] Get files (data, model) and earlier reports
- [x] Run model

2: Examine the analysis

- [ ] Check that data and results resemble earlier reports
- [x] Explore input: data types, files, etc.
- [x] Identify minimal set of files to run the assessment

3: Data script

- [x] Read data files
- [x] Preprocess data
- [x] Write TAF files

4: Input and model scripts

- [x] Prepare model input
- [x] Run model
- [ ] Document dependencies, especially non-CRAN packages

5: Output script

- [ ] Extract results of interest, e.g. N and F at age
- [ ] Construct summary table: Rec, SSB, Fbar, etc.
- [ ] Write TAF files

### Links to other issues?
NWWG 2018 TAF work #159
