### ISSUE TITLE
2018 North Sea & West of Scotland haddock

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#187]
### Summary
https://github.com/ices-taf/2018_had.27.46a20

### Tasks required
see: https://github.com/ices-taf/doc/blob/master/procedure.md

1: Get model to run

- [x] Contact assessment coordinator
- [x] Get files (data, model) and earlier reports
- [x] Run model

2: Examine the analysis

- [x] Check that data and results resemble earlier reports
- [x] Explore input: data types, files, etc.
- [x] Identify minimal set of files to run the assessment

3: Data script

- [ ] Read data files
- [ ] Preprocess data
- [ ] Write TAF files

4: Input and model scripts

- [x] Prepare model input
- [x] Run model
- [ ] Document dependencies, especially non-CRAN packages

5: Output script

- [x] Extract results of interest, e.g. N and F at age
- [x] Construct summary table: Rec, SSB, Fbar, etc.
- [ ] Write TAF files

### Links to other issues?
WGNSSK 2018 TAF work #156
