### ISSUE TITLE
Review of MSY ranges for roundnose grenadier in 5.b, 6, 7 ex. 12.b

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#196]
### Summary
Review of the calculations of MSY ranges follow the ICES guidelines

### Tasks required
- [x] revise how biomass dynamic model reference points are deemed to be precautionary
- [x] revise definition of MSY ranges
- [x] find other examples of biomass dynamic category 1 stocks

**Comment by colinpmillar** [comment]
Completed, but not required due to downgrading of RGN assessment to cat 5
