### ISSUE TITLE
Data's Den at the 2018 ASC: TAF pitch

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-taf/doc#197]
### Summary
The DIG sub-group on the Data’s den at the ASC were keen that the Data centre make a direct contribution. Seeing as the three of us are there, I think it would be good to do and I think TAF would make a good pitch. Just to recap, the idea is to pitch the idea at high level ICES people i.e. Bureau/Steering chair level in a short amount of time (4-5 mins). 

I had an idea of how we could run it in a fun and interactive way using DUPLO. 

**Part 1:**
The judges will be asked to recreate a DUPLO fish. The pieces of the fish will be held by various members in the audience, as will the instructions – the judges will need to run around collect the pieces/assemble against the clock i.e. 1 minute. A nuance could be that one of the pieces is the wrong colour but right shape – this will come back in Part 3

**Part 2:**
The judges will then repeat the exercise but this time they will be given the TAF box, which contains all the pieces and the instructions (could be a slightly different fish they make), once again having 1 minute

**Part 3:**
The pitch: this was of course a metaphor for reproducing assessment results, the bricks representing the input data, the instructions the methods – TAF is the way to record assessment inputs, models and outputs in ICES.  Notice the first fish is the right shape but has the wrong colour brick – TAF ensures that we have traceability, so that the data used in the exact instance of the assessment is what you get out of the box.

So we have to submit a proposal to Malin by 1st July, are you happy to go with this (will need some running around when we’re in the open session).

### Tasks required
- [x] Hjalte and Colin to get on board :)
- [x] Neil to submit proposal to Malin
- [x] Neil to find some DUPLO

![duplo](https://user-images.githubusercontent.com/23527005/40916171-03db9878-67ff-11e8-8d1c-7905071b5c8f.png)

**Comment by colinpmillar** [comment]
success :) 👍

**Comment by neil-ices-dk** [comment]
and for the record ;)
let's also see if we can get some pictures from Simon C

> Neil did a great job showing the participatory aspects of his transparent modelling framework he pitched. Transparency and participation of an extended peer community are important aspects of Responsible Research and Innovation, so that's a real winner for me! 4/4!

**Comment by neil-ices-dk** [comment]
btw - i'm thinking we should use some of Dorothy's quote "Transparency and participation of an extended peer community are important aspects of Responsible Research and Innovation" as a soundbite on some of our ppt's and posters

**Comment by colinpmillar** [comment]
SOunds good - linked to: FAO Rome event planning #212
