### ISSUE TITLE
Switch user authentication to Azure

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#198]
### Summary
ICES IT has moved active directory to the cloud so it is now possible to authenticate users through AZURE

### Tasks required
- [ ] investigate online resources: https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-webapp-openidconnect-aspnetcore/
- [ ] implement on test branch
- [ ] test with ICES staff and external users
- [ ] push to master
