### ISSUE TITLE
Restructure TAF API using GitHub as inspiration

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#209]
### Summary
V0.1 API was designed for a simple single repository.  The design for TAF now uses GitHub and linking to teams etc.  In order to accommodate this more complex logic, a new API structure is required, and the GitHub API provides excellent motivation.

### Tasks required (try and do in parallel)
- [x] Design basic structure with user, egs and analysis controllers
- [x] begin wiki documentation for API
- [x] begin R package to call APIs
- [ ] Upgrade web page to call new APIs

**Comment by colinpmillar** [comment]
Wiki development begun here:
https://github.com/ices-taf/doc/wiki/API-Overview

**Comment by colinpmillar** [comment]
API restructuring branch:
https://github.com/ices-taf/ICES.TAF.WebSite/tree/api-revision_1

**Comment by colinpmillar** [comment]
Closing. 

Issue to update the web page here:
Upgrade webpage to link to new api #246
