### ISSUE TITLE
Investigate use of git / svn repository for storing input and output

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#21]
Now broken up into
- [x] #113 restructure database
- [x] #108 Link analyses to GitHub
- [x] #109 develop git service
- [x] #110 develop service for GitHub api
- [x] #111 develop logic for using GitHub as central code repository
- [x] #112 implement logic for using GitHub as central code repository
- [x] #169 Implement online results via a results branch

**Comment by colinpmillar** [comment]
It is looking like this is a good option.  
* We will restructure the database to hold links to the files
* then TFS will deal with versioning of scripts and datafiles a like
* we can maintaining a working copy of the repo on the TAF server
* we can think about using a .gitigore file to only keep one version of some files like binaries...

**Comment by colinpmillar** [comment]
All done - now testing

**Comment by colinpmillar** [comment]
test case working on: 
https://github.com/ices-taf/DBreport_StockCategories/tree/server
