### ISSUE TITLE
Organise TAF workshop

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#210]
### Summary

Organise a 2 day workshop on putting stock assessments into TAF.  It would be run as a training workshop where attendees will be given hands on help with the aim of getting their assessment into the TAF structure, cleaning their code and linking their inputs and outputs to ICES databases where possible.

Target audience: Stocks assessments partial and complete in TAF during 2018 and those enthusiastic to work through the year.

### Tasks required

- [ ] Look at rooms and times for free space with @odontaster
- [ ] Send scoping email to potential participants to find out if they could come to ICES in the autumn winter 2018-2019
- [ ] Put together an informal email to send to chairs and ask them to circulate
- [ ] Invite TAF enthusiasts directly
- [ ] Invite REDUS folks as a follow up to ASC meeting

###  Notes 

* We could also invite professional officers
* Communication via Chairs and directly with those who expressed interest.
* Having a mixed set of stocks and problems would be good for the workshop and could encourage cross fertilization of ideas / solutions

**Comment by odontaster** [comment]
Atlantic and Baltic are quite busy until before Christmas. Much better after Christmas, we could probably choose any date until March-April.

**Comment by colinpmillar** [comment]
Thanks Adriana!  We will send an email round the chairs and people already involved in TAF to see if they are free (and interested!) then we will get back to you :)

**Comment by arnima-github** [comment]
This sounds great.
Adriana, can you check which weeks in January-February it would be possible to get the Atlantic Room?
Thanks!

**Comment by odontaster** [comment]
Hey guys,
January and February are getting packed in the Atlantic room (capacity 48 people)!!
Only free: 7-11 Jan, 28-30 Jan(Monday-Wednesday), 11-15 February(suspicious, maybe there is some bank holiday?)
Biscay is still big, up to 25 people, and now is free  7-18 Jan, 11-30 Feb and 1-22 March
Choose and I will block it! or maybe I will block them all! :-)
Let me know

**Comment by arnima-github** [comment]
Draft of email invitation:

***

*Subject: Invitation to ICES TAF workshop*

Dear WG chairs and members,

This year marked the first year that the ICES Transparent Assessment Framework (TAF) is used to organize and archive ICES stock assessments. The plan is to move the majority of ICES assessments into TAF over the next few years. The TAF developers (Colin Millar and Arni Magnusson) attended several assessment WGs in spring 2018, to support the first users to move their assessments into TAF.

We want to thank the WG members who worked towards getting their assessments into TAF this year. Many success stories involve assessments that are completely or partially scripted on TAF, and can be completed or rerun on TAF next year. Furthermore, the different WGs are growing in terms of TAF expertise, enabling colleagues to provide technical assistance within the group. We also want to thank the chairs for allocating time in the busy WG schedules for introducing TAF to the group members, both in plenary and in subgroups.

To follow up and further assist WGs to move assessments into TAF, ICES would like to invite any interested WG chairs and members to participate in a TAF workshop, to be held in March 2019. The objectives of this workshop will be:

1. Give an overview of existing analyses on TAF. These include fully completed assessments, partially completed assessments, data-limited stocks, and analyses that only focus on data preparation of survey indices, maturity, etc.

2. Demonstrate how assessments are moved into TAF. Assist people and answer any technical questions that arise.

3. Discussion and collection of user feedback. The design and development of TAF has already benefitted from user comments and requests, and continues to do so.

4. Talk about possible TAF badges to recognize assessments and users for various achievements. It is not a small task to make ICES assessments open and reproducible, thus improving the quality assurance and peer review process that ICES stands for. TAF aims to provide a working environment, but in the end it's the stock assessment experts who do the work and deserve credit for that.

We should be able to cover these topics in three days. At this point we would like to ask you to indicate whether you would be willing and able to attend, and which of the following days might work best for you: 4-6 Mar, 5-7 Mar, 6-8 Mar.

Looking forward to hearing from you,
Arni, Colin, Lotte, and Neil

**Comment by neil-ices-dk** [comment]
Clarification – what do you mean by members? Members of assessment WG’s? if so then the invitation should just be to WG participants and drop the WG chairs part.

**Comment by neil-ices-dk** [comment]
sorry guys, i had to take this into Word for ease of commenting/editing
[TAF-workshop.docx](https://github.com/ices-taf/doc/files/2541975/TAF-workshop.docx)

**Comment by Lotte-ices-dk** [comment]
Thanks, Neil, good edits. I agree with adding a doodle, that would also make the participants 'own' the actual dates, facilitating participation once we get there. 
One thing - when you actually have a time, then you would need to create ToRs and a draft resolution for ACOM approval (you know the usual paperwork) so the WK can get into the planning for next year.

**Comment by colinpmillar** [comment]
Just in case, adriana booked: 
* Kattega - 16-22 Feb
* Baltic 11-12 March

She also pointed out that the proposed week we have in there (4-8th March) is during ACOM

**Comment by colinpmillar** [comment]
Hi,

here is the updates from November last year: invitation with a doodle poll added and a draft set of ToRs

[WKTAF_draft_resolution.docx](https://github.com/ices-taf/doc/files/2745073/WKTAF_draft_resolution.docx)
[TAF-workshop-invitation.docx](https://github.com/ices-taf/doc/files/2745094/TAF-workshop-invitation.docx)

I was wondering if we wanted to give more push to the practical nature of the workshop and a bit less on discussion?  Or at least give them equal weight in the ToRs

Dates are now proposed to be: 
18-19 February and 18-19 March

But this will prossibly need to be pushed back a little

**Comment by colinpmillar** [comment]
here is the slide Mark presented at ACOM for info:
![taf_workhop_slide_acom_2018](https://user-images.githubusercontent.com/1502848/50966604-b7750580-14d5-11e9-883a-9c249a6580a3.png)

**Comment by Lotte-ices-dk** [comment]
I think, you guys have been very operational with the groups last year and that paid off, so if you like to have more emphasis on this part, then you need to reflect this in the ToRs, yes. What I know is that the point 'quality assurance' was of high interest in ACOM and could also make the tool more attractive to the users, so it should stay in the ToRs as a point; could be merged with 'discussion and feedback' if need be.

**Comment by neil-ices-dk** [comment]
Apologies for forgetting this one - comments on the WK resolution attached. 
[WKTAF_draft_resolution.docx](https://github.com/ices-taf/doc/files/2745340/WKTAF_draft_resolution.docx)
