### ISSUE TITLE
Develop a short example of AcousticTAF workflow

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#211]
### Summary

Develop a short example of AcousticTAF workflow for presentation at a meeting with REDUS at the ASC 2018 and to the WGIPS in January 2019

### Tasks required
- [ ] link to acoustic data portal web service
- [ ] code up a mock analysis with results
- [ ] make a diagram of the workflow for presentation at ASC and to WGIPS in January

**Comment by colinpmillar** [comment]
From Medhi:
Hi Collin,

These are Acoustic WebAPI for downloading StoX files:
1.	List of all submission -> http://acoustic.ices.dk/services/Download/GetUploadlist/
This service returns list of submitted cruise. You can get id for each cruise and pass to the bellow services to download Acoustic or Biotic StoX files.

![acoustictaf](https://user-images.githubusercontent.com/1502848/45689269-db41c380-bb53-11e8-9698-e3671890e633.jpg)


2.	Download Acoustic StoX file -> http://acoustic.ices.dk/services/Download/DownloadStoXAcousticXML/{ID}
eg. http://acoustic.ices.dk/services/Download/DownloadStoXAcousticXML/3

3.	Download Biotic StoX file ->  http://acoustic.ices.dk/services/Download/DownloadStoXBioticXML/{ID}
eg. http://acoustic.ices.dk/services/Download/DownloadStoXBioticXML/3

**Comment by colinpmillar** [comment]
Here is the second version of the diagram for the workflow:
![taf_with_begin_script_v2](https://user-images.githubusercontent.com/1502848/45813009-bb380e80-bcd1-11e8-8c63-9cd53aedc731.png)

**Comment by colinpmillar** [comment]
@HjalteParner  - does "Bootstrap" work better for you than begin?

**Comment by HjalteParner** [comment]
Much better (to me)

**Comment by HjalteParner** [comment]
> @HjalteParner - does "Bootstrap" work better for you than "begin"?

Bootstrap is a good word to me e.g. 'In computer technology the term (usually shortened to booting) usually refers to the process of loading the basic software into the memory of a computer after power-on or general reset, especially the operating system which will then take care of loading other software as needed.'
