### ISSUE TITLE
FAO Rome event planning

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#212]
### Summary

Planning tasks for the TAF side event at the FAO fisheries symposium in Rome, December 2018

Programme for event: http://www.fao.org/gfcm/fishforum2018/programme/en/

### Tasks required
- [x] Ask Communications to come to TAF meeting about Rome FAO side event.
- [x] Invite someone from Comms to help at Rome (Tues 11th December): likely to be Olle
- [x] Design banner (@Terhinator)
- [x] Develop new flyer, 2/3 page small brochure
    1. why taf - get from bureau doc
    2. what is TAF - ices annual report TAF page
    3. links to taf.ices.dk - video, tutorial, sample assessments
- [x] Plan what food to provide (@Lotte-ices-dk to check)
- [x] Draft a presentation (@arnima-github, @colinpmillar)
- [x] send agenda to Ahmed at FAO by 21st Sept (@arnima-github, @all)

#### other actions
- [x] @colinpmillar: ask about size / layout of room in FAO
- [x] @colinpmillar: add Terhi to GitHub
- [x] @colinpmillar: Resurect taf.ices.dk page revision task - link: https://github.com/ices-taf/doc/issues/142

### Notes

* make it dynamic, enourage audience participation
* Open with Data's Den 5 min presentation on TAF

**Comment by colinpmillar** [comment]
Potential for a Stand in the FAO attrium:
![stand_example_fishforum_july2018](https://user-images.githubusercontent.com/1502848/45684636-3c16cf00-bb47-11e8-9962-00695e0ecfe9.jpg)
* The only costs that you will have is related to the realization of the panels that will be putted on the table that will be prepared by an external supplier with a cost of 220 euro approximately
* It is requested to have a person that will stay at disposal for all the time of the Forum (10-14 December)
* Roll-up are not allowed in the FAO Atrium and we will need to receive in advance copy of the communication material together will a list of the material to be presented by the middle of October.

**Comment by Lotte-ices-dk** [comment]
Indeed - who's the blond? Anyway - this confirms that we only would need an extra 'drop-down' (is this what you call that posterthingy?) and some folders, data decks and uhm..I don't know, something else? Do we have more paper stuff?

**Comment by neil-ices-dk** [comment]
probably an ICES brochure or the annual report to pad things out a bit :)

**Comment by arnima-github** [comment]
Continuing from email thread, here's the updated agenda:

**Comment by arnima-github** [comment]
**Open and transparent science for fisheries management:**
*Introducing TAF (Transparent Assessment Framework), an online environment to organize stock assessment data, models, and results*

**Agenda**
* Opening pitch, with audience participation (10 mins)
* Overview of topics - reproducible research, open data, peer review, quality control (30 mins)
* Interactive discussion with audience - experiences, challenges and solutions (20 mins)
* Online demonstration of TAF - webpage, functionality, input data, analysis, output tables/plots (20 mins)
* Continued discussion (10 mins)

**Comment by colinpmillar** [comment]
Looks good to me :) - I would drop the final discussion and end on the demo - we can always take questions as we go.

**Comment by colinpmillar** [comment]
Presentation plan going here:
https://github.com/ices-taf/doc/blob/master/taf-side-event.md

**Comment by colinpmillar** [comment]
pretty much good to go :)
