### ISSUE TITLE
Set out how TAF will generate DOIs for stock assessment outputs

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#214]
### Summary

* What information (meta-data) will be needed to in order to generate DOI's for stock assessments and stock assessment results

* How will we deal with in year updates to assessments

* How will this relate to SAG DOI's

### Tasks required
- [ ] What will a TAF assessment DOI point to, and what information / meta data will we present
- [ ] When will DOIs be generated (at publication and if there are updates)
- [ ] Do we link to SAG DOIs from TAF?

### Links to other issues

https://github.com/ices-tools-dev/DOI/issues/15
Use releases to add data to a published TAF assessment #155
