### ISSUE TITLE
Finalise branch structure on github

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#216]
### Summary
What branches should we have, what are thier purpose and what protection should they have

THis is almost finalised, we just need a final agreement:
* taf branch - holds official run
* master/user branch - holds user uploaded code and results
* clean branch - convenice branch holding only code and initial input data

### Tasks required
- [x] finalise name of master - is it user or master
- [x] document in a markdown file in the doc repo
- [x] implement on services

**Comment by colinpmillar** [comment]
Agreed on:

* taf branch - holds official run - **set as default branch**
* user branch - holds user uploaded code and results from the user / stock assessor

### notes 

leave clean for now - can return to this at a later date

:)

**Comment by colinpmillar** [comment]
Documentation:
https://github.com/ices-taf/doc/blob/master/repository-branch-structure.md

Code changes:
https://github.com/ices-taf/ICES.TAF.WebSite/commit/e7f11ccb8f1590aae2d7c5a56821fefab9442d48
