### ISSUE TITLE
Develop and R package to link to TAF API

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#221]
### Summary

write an R package that allows the user to query, post and update TAF assessments

### Tasks required
- [ ] develop token system for package
- [ ] write functions in consistent style
- [ ] documentation and example
- [ ] release on CRAN

### Links to other issues?
requires: Restructure TAF API using GitHub as inspiration #209
