### ISSUE TITLE
Update TAF diagram in all documentation

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#223]
### Summary

Update diagrams for TAF to the ones developed by Olle:

http://ices.dk/SiteCollectionImages/Forms/Thumbnails.aspx?RootFolder=%2FSiteCollectionImages%2FTAF

### Tasks required
- [x] look through existing documentation and webpages
- [x] update with the relavent diagram
- [ ] identify if we need to ask for some updates / extensions to the base diagram
