### ISSUE TITLE
Stress test web application server

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#229]
### Summary

To stress test the server, set up a script to call the api as multiple users and both make changes, and run assessments.

### Tasks required
- [ ] find a hack to fake users
- [ ] develop test script to do some basic actions
- [ ] find out how to monitor the server and record how long things take
