### ISSUE TITLE
Get TAF servers on DMZ

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#230]
### Summary

Work with Mike to get the TAF web page, core services and run services in front of the firewall

### Tasks required
- [x] Make sure application is secure and all routes in require authentication
- [x] Set up a server for the web page and core services
- [x] set up an isolated server for the run services as this one is open to attacks

**Comment by mikeydrew** [comment]
Will set up new web-server to host TAF production website and services - Adminweb03.
Need new rules set up in the Firewall so that this new web-server can access, TAF.ices.local and related SQL server(s).
When going live, will change DNS settings accordingly for taf.ices.dk

**Comment by colinpmillar** [comment]
Done, done and done! :)

Will get an ssl certificate and then an external IP and we are good to go
