### ISSUE TITLE
Webhooks from GitHub

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#231]
### Summary

Set up and test the issuing of webhooks from TAF repositories when a commit comes in to the master branch, and the resulting web api call to pull, run and push the assessment back to the taf branch

### Tasks required
- [x] Set up webhook
- [x] test the web service responds
- [x] test the procedure commit - hook - pull - run - push

**Comment by colinpmillar** [comment]
Web hook created:
https://github.com/organizations/ices-taf/settings/hooks

**Comment by colinpmillar** [comment]
webhooks are linked :)

**Comment by colinpmillar** [comment]
It works! :)
![image](https://user-images.githubusercontent.com/1502848/49691556-3973b680-fb45-11e8-9dbf-4b427f0b0c06.png)
