### ISSUE TITLE
Develop 'Boss Mode'progress page on web app

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#235]
### Summary

This page allows a user to visualize the progress of a group of TAF assessments on one page, for example all the assessments in a stock assessment working group.  Progress will be defined by whether there are the correct input and results files etc.

### Tasks required
- [ ] Use the indicators returned from the R function developed in #234
- [ ] implement an api to run this check
- [ ] design the page using AngularJS
- [ ] test

### Notes

We could run the QC check after every run, and store the results.  Then we could just implement an api that queried the last 'status' of the analysis

### Links to other issues?

Will rely on the results of running:
R Functions / logic to check assessment progress #234
