### ISSUE TITLE
Upload age tables to SAG?

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#238]
### Summary

Just as a test, we could add a table to the SAG database to test the idea, and to a test upload.

### Tasks required
- [ ] provide an example dataset using an existing stock
- [ ] Draft a new format spec for DATSU
- [ ] Add table to SAG DB
- [ ] implement in DATSU (Anna O)
- [ ] add functionality to icesSAG development branch
- [ ] test
