### ISSUE TITLE
Develop a link between Accessions and TAF for WGMIXFISH

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#241]
### Summary

The ideal situation for the WGMIXFISH stock coordinator is
1. New submissions are copied to the WGMIXFISH Accessions folder on sharepoint (already happening)
2. This kicks of the automatic creation of a QC report for each new submission
3. (optional) once the data has passed the QC it is flagged somehow
4. Whenever new / updated data appears in the WGMIXFISH Accessions folder, the data collation script is run and the results uploaded to [ices-taf/wgmixfish_accessions](https://github.com/ices-taf/wgmixfish_accessions)

### Tasks required
- [ ] Link the WGMIXFISH accessions folder to the TAF QC repository for that country / submitter, so that new submissions get new QC reports
- [ ] Link the WGMIXFISH accessions folder to the TAF data prep repository: [ices-taf/wgmixfish_accessions](https://github.com/ices-taf/wgmixfish_accessions)
- [ ] Then implement, whenever new data is uploaded to the accessions folder, run the repo to update the collated files

**Comment by colinpmillar** [comment]
@ices-taf/wgmixfish - just mentioning you guys in case you want to follow the thread :)
