### ISSUE TITLE
Publish some TAF stocks

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#248]
### Summary
Draft some guidelines on how we publish some < 2018 TAF assessments, and make the code available through our web application.

Because we want to be able to keep some data private (via a feild in the CITATIONS file) we can;t simply make the github repo public.  So the way we have most control is to keep the repository private and make elements of it public via taf.ices.dk/app

### Tasks required
- [ ] collate a list of potential issues with publishing an assessment and its data
- [ ] develop a check list on how to publish an assessment
- [ ] test out on a few stocks from 2015 - 2017

### Links to other issues?

Set out how TAF will generate DOIs for stock assessment outputs #214
