### ISSUE TITLE
Develop api to access assessment datasets

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#249]
### Summary

See for example:
https://data.marine.gov.scot/api/3/action/package_show?id=c42d9bed-a9e9-4caf-bee9-fa71ec270f68

for a way to structure a request to ask for a list of datasets

### Tasks required
- [ ] develop framework to store the datasets
- [ ] write api to access metadata
- [ ] write api to access files

### Links to other issues?
#239  Citations file: how do we define and reference what data is used
