### ISSUE TITLE
Allow user to run a script to pull in data

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#263]
### Summary
this would work like:
```r
@Misc{[name],
  originator = {WGEF},
  year       = {2015},
  title      = {Survey indices: IBTS1, IBTS3, Unknown, and UKBTS3},
  period     = {1977-2015},
  source     = {script},
}
```
the `name` allows us to trace the directory or file that the record is referencing.

### Tasks required
- [ ] scope out ideas on how to implement
- [ ] test and implement in R
- [ ] test and implement on TAF server

**Comment by colinpmillar** [comment]
from @arnima-github:
I've created a basic pathway to run a custom bootstrap data script. See current version of icesTAF on GitHub (master branch is currently same as develop). The corresponding test analysis is at https://github.com/ices-taf-dev/bootscript.

I experimented with several variations of source(local=TRUE), sys.source(envir=new.env()), local(source()), etc. After getting dizzy with that, I couldn't see a major risk from running a simple source(), so that's the current implementation. I vaguely remember some problems that arose with sourceTAF() when I was doing similar experiments with sys.source and friends, so I ended up going back to simple source() as reflected in icesTAF commits from 2018-03-19.

When we brainstormed about a possible source = {script} functionality the other day, we did mention some ideas about the script having the same name as the output RData file (or RDS file). I'm wondering how much we would gain from that police work. The current implementation is really simple; it allows the custom script to have any name and create any kind of files. The taf.bootstrap + process.bib functionality is by far the most complicated part of icesTAF, and there is some value in trying to keep the code and functionality simple, so it doesn't become difficult to understand, explain, maintain, and modify in the future.

Custom bootstrap scripts will probably be the exception and as far as I can tell, misusing custom bootstrap scripts should be at least as rare as misusing other TAF scripts. Let's look into some of the custom bootstrap use cases that we know of, and explore how they would be handled in the current implementation.

**Comment by colinpmillar** [comment]
some potential ways forward:
* simple source
* variations of source(local=TRUE), sys.source(envir=new.env()), local(source()), etc
* source = {script}, forceing output to be the same name as the script.  all output could be put in a folder of the same name as the script

We could also screen the bootstrap/data folder for files or folders that are not reference in the DATA.bib file and warn or delete them

**Comment by colinpmillar** [comment]
I am thinking the following rules could be simple enough to implement, by example:
```r
@Misc{datras,
  originator = {ICES},
  year       = {2019},
  title      = {Survey indices: IBTS1, IBTS3, Unknown, and UKBTS3},
  period     = {1977-2019},
  source     = {script},
}
```
Rules:
* assume the existence of an R script `datras.R`.
* the script can run in isolation
* all files created by the script are placed inside `bootstrap/data/datras/`
* if someone wants to download this from outside of ICES, they will get a zip of the folder
and the metadata will show the type as a "collection".

**Comment by colinpmillar** [comment]
brainstorming:
* the R script produces files in the working directory
*`process.bib` will set the working directory accorfingly

instruction to user: "please do not specify target directory"
