### ISSUE TITLE
Allow DATA.bib to process multiple files in one record

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#264]
### Summary
Allow user to reference and download multiple related data files or scripts into one folder.
Structure would be:
```r
@Misc{functions,
  originator = {HAWG},
  year       = {2019},
  title      = {Functions related to short term forecast},
  version     = {2019, commited on ...},
  prefix = {https://github.com/ices-eg/...}
  source     = {
    script1.R
    script2.R
  },
}
```
*NOTE* the `prefix` simlifies the `source` field text.

As this is a `SOFTWARE.bib` all the entries in `source` will be put in the the folder
`bootstrap/software/functions/`

If this was a `DATA.bib` entry, it would go to in `bootstrap/data/functions/`

### Tasks required
- [ ] scope ideas and test
- [ ] decide on final implementation
- [ ] implement in `icesTAF`

### Links to other issues?
Allow user to run a script to pull in data #263

**Comment by colinpmillar** [comment]
from @arnima-github - it is also useful to include a `dir` feild in the `.bib. entry to force the file to be writen to a directory.  This is when there are two or more files with the same name, such as:
https://github.com/ices-taf/2019_ple.27.21-23_review/blob/master/bootstrap/DATA.bib
