### ISSUE TITLE
Build a TAF repo page

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#271]
### Summary
A page in the TAF app where you can select input datasets and software and it builds your bootstrap folder for you and includes some basic data.R, and report.R code to read and plot some datasets.

### Tasks required
- [ ] scafolding code for bootstrap
- [ ] snippets for plots attached to specific datasets
- [ ] list of recomended packages to go with datasets (ie icesFO, icesSAG, etc)
