### ISSUE TITLE
VMS data request 2021 WGCRAN

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#279]
From @LaraSalvany 
Background info: For the past 2 years WGCRAN requests NL, DK, BE and DE:

monthly cumulated values for fishing effort (hours) and total landings (tonnes) at a resolution of 0.05 x 0.05 degrees (…) These values are needed for one metier (TBB_CRU_16-31) for the years 2009 – 2020 and the geographical scope is the Danish, German, Dutch and Belgian EEZ’s.

Please see attachment for full VMS data request: [link](https://teams.microsoft.com/l/file/C528F828-F0FC-40F6-96FB-09D86FE1FF2E?tenantId=e0b220ce-5735-4468-91df-05cae5ff1fdc&fileType=docx&objectUrl=https%3A%2F%2Ficesit.sharepoint.com%2Fsites%2FICESsecretariat%2FShared%20Documents%2FTAF%2F20210825_VMS%20Data%20request_WGCRAN.docx&baseUrl=https%3A%2F%2Ficesit.sharepoint.com%2Fsites%2FICESsecretariat&serviceName=teams&threadId=19:1ebf7820ca5844e2bebbac6c7eea4679@thread.tacv2&groupId=6b1bf702-c748-4eeb-afb2-f2af65696271)

Last year Colin set up a code, extracted the data, uploaded to the WGCRAN SharePoint and gave support to the experts.  
The plan this year is that Cecilia takes over and Colin helps/supervises her.

Could you please start prepping on this? I will get back with an exact date when the data is needed as soon as I get the response from Claudia, the chair of WGCRAN, but you can have some VMS fun in the meantime 😊?

## ToDo
@colinpmillar 
- [x] make repo for request: 2021_WGCRAN_adhoc-vms-data
- [x] update code: remove NLD special treatment from 2020 request
- [x] update code: unique vessel / anonymity feilds
- [x] check VMS extraction code in VMS DB (issuees from FOs need resololved)

@cekv
- [x] install packages
- [x] run and do some exploratory checks, possibly in a report_qc.R
- [x] provide to Lara / WGCRAN
